services:
  - type: web
    name: project-kassandra
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
